### PR TITLE
My first pull request

### PR DESCRIPTION
**Pull request by pickfire**
- Simplify response with json
- Replace title in content
- Format with clippy
- Use reqwest::Url to generate params
- Remove unneeded parse_arguments
- Add instructions in default layer
- Check LANG before default to en

### CODE REVIEW

**Comment by oppiliappan** [comment]
Using `reqwest::Url` had always been on my TODO list. Thanks for adding it!

**Comment by pickfire** [comment]
@NerdyPepper Cool, thanks for starting a nice project. Any other stuff in the TODO list?

**Comment by oppiliappan** [comment]
An ASCII banner and a more complete command line interface.

I have also been thinking about a  design change:  
Items in the quick links sidebar, when clicked, open a small window with a preview, and can be expanded to a full article, or closed.

**Comment by pickfire** [comment]
What about links in the article?

**Comment by oppiliappan** [comment]
The links in the article are currently displayed in the side bar.

**Pull request merged**
